// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuCIMPwd_VbkkkYn9lFm_KroQBbAIvF-8',
    appId: '1:744126678858:web:cb187d3679e48c1bf563b3',
    messagingSenderId: '744126678858',
    projectId: 'notess-app-21fee',
    authDomain: 'notess-app-21fee.firebaseapp.com',
    storageBucket: 'notess-app-21fee.appspot.com',
    measurementId: 'G-CPMCS9PM8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPYc-TdlPOcHWtxGjVzmXE0b1d87-V1zY',
    appId: '1:744126678858:android:64e64b8f5bcba998f563b3',
    messagingSenderId: '744126678858',
    projectId: 'notess-app-21fee',
    storageBucket: 'notess-app-21fee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGNP6KEVgemIGCSLXZ5lr97Bhlk-LlUX4',
    appId: '1:744126678858:ios:3dc9d860fa1b581cf563b3',
    messagingSenderId: '744126678858',
    projectId: 'notess-app-21fee',
    storageBucket: 'notess-app-21fee.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGNP6KEVgemIGCSLXZ5lr97Bhlk-LlUX4',
    appId: '1:744126678858:ios:12995b3af72c15faf563b3',
    messagingSenderId: '744126678858',
    projectId: 'notess-app-21fee',
    storageBucket: 'notess-app-21fee.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
