// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwV6IvHk9X146RpWY7LRKpg21_LyL-o14',
    appId: '1:920845208751:web:7b0a5e4f9b24f16425185a',
    messagingSenderId: '920845208751',
    projectId: 'notes-app-66140',
    authDomain: 'notes-app-66140.firebaseapp.com',
    storageBucket: 'notes-app-66140.appspot.com',
    measurementId: 'G-Z8WB3CFYW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk_sxgsmGSR7F09glim5_eZsGmVzHiyNE',
    appId: '1:920845208751:android:2c8b3b606ef3f3d425185a',
    messagingSenderId: '920845208751',
    projectId: 'notes-app-66140',
    storageBucket: 'notes-app-66140.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_mo7DEcUAx-U-povXiws8SkJy9LgeqO4',
    appId: '1:920845208751:ios:e96f2e310fdea58a25185a',
    messagingSenderId: '920845208751',
    projectId: 'notes-app-66140',
    storageBucket: 'notes-app-66140.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_mo7DEcUAx-U-povXiws8SkJy9LgeqO4',
    appId: '1:920845208751:ios:fd28f4093876865b25185a',
    messagingSenderId: '920845208751',
    projectId: 'notes-app-66140',
    storageBucket: 'notes-app-66140.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
